import Footer from "@/components/main/footer";
import Header from "@/components/main/header";
import Head from "next/head";
import React from "react";

export default function Layout(props) {
  return (
    <div>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {props.children}
        <Footer></Footer>
      </main>
    </div>
  );
}
